name: flutter_tdd
description: Articles App clean Architecture


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State Management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  # Functional Programming
  dartz: ^0.10.1
  # Value Equality
  equatable: ^2.0.3
  # Service Locator DI
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.4
  # Local Storage
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
